### ISSUE TITLE
Tamil Support

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#16]
EDITED
- [x] Add Tamil sources files
- [x] Add Tamil feature files/GOADB (@paarandiak)
- [x] Set glyph names to global structure to match GOADB  #30
- [x] Check vertical matrix and set
- [x] Design Improvements 
- [x] Check Interpolation
- [x] Debug interpolation
- [x] Update copyright notices (On repo, source files, OFL, tables)

**Comment by davelab6** [comment]
This may need to go in a 2nd family.

**Comment by pathumego** [comment]
Sinhala and Tamil don't share Unicode points. Is it possible to ship it
combined? Or is it like Latin+ somescript

**Comment by pathumego** [comment]
@davelab6  Tamil dose share unicode points /zwj and /nzwj is there. So how should it be? A separate repo for Tamil I guess? If so we have to have separate repos for other Tamil projects too I guess.

**Comment by davelab6** [comment]
Yeah I think for now lets ship them as 2 families. Do you want to keep the Abhaya family name for both? I'm not sure... up to you :)

**Comment by davelab6** [comment]
I guess that eventually the W3C will fix unicode range, and then we can ship combined families and de-list the duplicates

**Comment by pathumego** [comment]
From the Google Fonts mailing list 

 ```
1. Should we have two separate repos for this?
2. Or treat it as a one family in production(in same repo, under same family name) and only consider it as two families for Google Fonts shipping?  
3. Can we keep the same family name for both fonts?

In the Fonts API, you can't have the same name for both families... perhaps use Abhaya Libre for the Latin + Sinhala and Something Libre for the Latin + Tamil? Or Abhaya Libre for Latin + Sinhala and Abhaya Libre Something or Abhaya Something Libre for the Latin + Tamil?

Do the overlapping unicodes need to be different? If not, I suggest that (2) can be better - you develop a single repo and build combined font binaries, and use pyftsubset and fontTools to split and rename them into latin-plus-another-script pieces.
```

**Comment by pathumego** [comment]
This is progressing in https://github.com/mooniak/abhaya-libre-font/tree/dev

**Comment by pathumego** [comment]
Google Fonts can now ship this as a single family. With AbhayaL Libre version 2 we will ship Sinhala, Tamil and Latin in a single family. Tracking progress here #67
