### ISSUE TITLE
Review of release 1.0.0 that leads to 1.02

### ISSUE THREAD

**Issue by davelab6** [mooniak/abhaya-libre-font#20]
I reviewed https://github.com/mooniak/abhaya-libre-font/releases 1.0.0 release.

- [x] sadly the OpenType spec doesn't allow a 3rd period in version numbers, like `X.Y.Z`, only `X.Y`. You already make 1.001 and I made 1.002, so make the next release 1.003 :)

- [x] You **MUST** include a copy of the OFL in the release ZIP next time! :) 

- [x] Copyright notice in the files is

```
      Copyright (c) 1996-2015 Pushpananda Ekanayake (pushpanandae@gmail.com) Copyright (c) 2015 Sol Matas(sol@sonnenshine.com.ar) Copyright (c) 2015 Mooniak (hello@mooniak.com)
```

it should be (note the space after `Matas`)

```
      Copyright (c) 1996-2015 Pushpananda Ekanayake (pushpanandae@gmail.com) Copyright (c) 2015 Sol Matas (sol@sonnenshine.com.ar) Copyright (c) 2015 Mooniak (hello@mooniak.com)
```

- [x] FontForge says, `The glyph named uni0020 is mapped to U+F033A. But its name indicates it should be mapped to U+0020.` I didn't investigate. 

- [x] Your OTFs OS/2 table (e.g. the Bold) has

```
    <sTypoAscender value="800"/>
    <sTypoDescender value="-200"/>
    <sTypoLineGap value="200"/>
    <usWinAscent value="850"/>
    <usWinDescent value="350"/>
```

This is close, but isn’t quite right, because the v metrics of a web font should be the bounding box of the _family_ so that when you have multiple styles on one line, the line height doesn’t change. Currently for the OTFs this would be in `OS/2` (and in `head` the `hhea` values also all the same):

```
    <sTypoAscender value="860"/>
    <sTypoDescender value="-348"/>
    <sTypoLineGap value="0"/>
    <usWinAscent value="860"/>
    <usWinDescent value="348"/>
```

However, this causes problems with desktop apps, so for the OTFs I recommend keeping these metrics and only having the 'bbox' metrics for the TTFs.

```
$ fontbakery-fix-vertical-metrics.py SomethingSans-Regular.otf 
Parameter              SomethingSans-Regular.otf    
ymax                   960                        
hhea.ascent            960                        
OS/2.sTypoAscender     750      // note
OS/2.usWinAscent       960                        
ymin                   -253                       
hhea.descent           -253                       
OS/2.sTypoDescender    -250     // note
OS/2.usWinDescent      253                        
hhea.lineGap           0                          
OS/2.sTypoLineGap      213      // note
hhea total             1213                       
typo total             1213                       
win total              1213                       
UPM:Heights            1000:1213                  
UPM:Heights %          121 %   
$
```

Its important that the totals all add up to the same, and the sTypoAscender + sTypoDescender = the UPM, with the sTypoLineGap being what ever is needed for all 3 to sum to the box. You see this here:

```
hhea total             1213                       
typo total             1213                       
win total              1213                       
```

I'll email Pathum with a ZIP of the OTFs and TTFs for 1.02, and then you can make a 1.04 based on these and the fixes in your 1.01

**Comment by pathumego** [comment]
cc @paarandika

**Comment by pathumego** [comment]
@davelab6 Thanks!

**Comment by paarandika** [comment]
@davelab6 I have added the values in to OS/2 table and fixed the copyright notice(https://github.com/mooniak/abhaya-libre-font/commit/8e567a6f3a8b375ee2d0e13cb5bb45f92c4e3058). And I'm hoping to change the unitsPerEm value in fontinfo.plist and correct naming issue with "uni0020". But I couldn't find a place where  UPM:Heights, UPM:Heights % fits into. And I couldn't add yMax and yMin values to head table. AFDKO spits an error when I add them. Can you please clarify me above things a little? Thanks :)

**Comment by davelab6** [comment]
I updated the description, https://github.com/google/fonts/commit/8245e7e50ae49e93ee46c4df8c194f5e50a46996

**Comment by davelab6** [comment]
> I have added the values in to OS/2 table and fixed the copyright notice(8e567a6). 

That looks good!

> And I'm hoping to change the unitsPerEm value in fontinfo.plist 

I don't know why you would do this. 

> and correct naming issue with "uni0020"

:)

> But I couldn't find a place where UPM:Heights, UPM:Heights % fits into

Its implicit. 

1. The UPM value is specified in the fontinfo.plist ([eg](https://github.com/mooniak/abhaya-libre-font/blob/master/sources/AbhayaLibreLatin-Regular.ufo/fontinfo.plist#L82-L83)), but it is really just a tip for the context of the glyphs' point positions. 
2. The heights are the sums of the vertical metrics. 
3. So the upm:heights ratio is (1) to (2); and that can also be represented as a percentage. 

> I couldn't add yMax and yMin values to head table. 

Those are also implicit, known by looping over every glyph in the font and rendering it and measuring the highest/lowest bounds. The values are cached in the `head` table, and calculated by the font compiler; you can't specify or override them.

**Comment by davelab6** [comment]
>  fixed the copyright notice(8e567a6).

You also need to update the UFOs and other font files. 

https://github.com/mooniak/abhaya-libre-font/blob/master/sources/AbhayaLibreLatin-Regular.ufo/fontinfo.plist#L10

**Comment by davelab6** [comment]
I edited the first message in the thread

**Comment by pathumego** [comment]
Was fixed with https://github.com/mooniak/abhaya-libre-font/releases/tag/1.030
