### ISSUE TITLE
/percent (%) is not correct

### ISSUE THREAD

**Issue by davelab6** [mooniak/abhaya-libre-font#21]
In 1.0.0 release, the `/percent` glyph is incorrectly encoded as the `/hundredths` glyph:

<img width="67" alt="screen shot 2015-09-11 at 18 22 10" src="https://cloud.githubusercontent.com/assets/261579/9842249/ae5fe330-5a79-11e5-9471-0ef0d38def54.png">

**Comment by davelab6** [comment]
cc @solmatas

**Comment by solmatas** [comment]
In my file there are these two glyphs:
_ percent (0025)
_ perthousand (2030)

I will check with Pathum this.

<img width="683" alt="percent" src="https://cloud.githubusercontent.com/assets/8105496/9850015/1efcb156-5af0-11e5-9a8a-07be0a4196fe.png">

**Comment by pathumego** [comment]
@davelab6 @solmatas I checked. I will fix this. In final UFO here `https://github.com/mooniak/abhaya-libre-font/tree/master/documentation/development/25-08-2015/ufo/Abhaya%20Libre%20Latin-Regular.ufo` These glyphs were messed up, I fixed them, but seems like it dose not align properly eve if I fix it few times, it keeps exporting the UFO like in the image. I don't know if it a bug with GlyphsApp. But Used components are all aligned to baseline here.

 So Im decomposing these and will add an updated glyphs file to the `/sources/glyphs/` folder.

<img width="430" alt="screen shot 2015-09-15 at 9 51 03 am" src="https://cloud.githubusercontent.com/assets/6846609/9867862/b49c0abe-5b8f-11e5-81e7-5cac7ac4ba7f.png">
