### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#23]
Anura Tissera wrote on `http://sourceforge.net/p/sinhala/mailman/sinhala-technical/` (Extract only)
 
- [ ]  This Font was licensed by FM to ANCL (Lake House) for use on Silumina Classifieds (trust it is still in use). to get a closeer character height with the English font we used (when mixed) in print, we scaled the font by 20% (if I remember right). however it was not enough (I felt later). I see that problem on your font, but not as significant as it was - but has room for improvement ... I guess

- [ ] The Sinhala characters in general have curved bases (similar to English characters like 's' 'e' 'o' etc... ) .. if you see closely you will notice the Sinhala characters are slightly elevated than the English characters, to overcome that we did a baseline off set (-5 to -10 RUs if I remember right ) - it is a tedious process as each glyph need this correction. (look at a good English font in a Font development package, you'll see the offset on 'rounded base English characters.

- [ ] . incidentally, the accented characters with 'repaya' needs slight elevation adjustments.. and 'mahaprana ja' looks like a made-up (two glyph combined) character where as it has a separate glyph.. similar aesthetic improvements are required... to make it better!

in my opinion: overall it is good, but can be improved as this is the best fast reading font in Sinhala (counter part of Times Roman)... you may need to put a little more effort and improve this.

**Comment by pathumego** [comment]
Closing, this was posted here for documentation purposes. I personally dont agree with most of it. But some things could be revisited later

**Comment by davelab6** [comment]
Cool, great to see that list :)
