### ISSUE TITLE
Organise repo to new build system

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#24]
@paarandika  Since we have the tamil files with us, better to set up the repo to accommodate the full buid with the vagrentbox

**Comment by pathumego** [comment]
@paarandika I created a new branch https://github.com/mooniak/abhaya-libre-font/tree/tamil-combined-build to add Tamil and work on the combined Welipilla build. Tamil files are already in the sources folder. Can you set up the build?

Then we can move forward with #16

**Comment by paarandika** [comment]
Why new branch? Repo organizing is neither new feature nor major change.

**Comment by pathumego** [comment]
Okay :) lets set up welipilla then

**Comment by pathumego** [comment]
But since we are adding tamil to the build and introducing new build environment i think it should be considered as a new feature and major change too :)

**Comment by paarandika** [comment]
We do not change the out come or the product. And there will be number of conflicts to handle if we use separate branch for re-organizing the repo. I'll do it in master and for tamil we will use another branch.

**Comment by pathumego** [comment]
oki :)

**Comment by paarandika** [comment]
Don3 :)

**Comment by pathumego** [comment]
@paarandika I dont see the /features files and GOADB and vagrant files :)
