### ISSUE TITLE
Feature error

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#31]
Line 23 of feature file has a bug:

` sub si_Tta si_Halant zwj si_Tha by si_TtTtha`

Should be 

 ` sub si_Tta si_Halant zwj si_Ttha by si_TtTtha` 

@paarandika Please check with @pushpananda about this.

**Comment by paarandika** [comment]
This is the glyph in question
![ttttha](https://cloud.githubusercontent.com/assets/6725097/10358704/d2ee856a-6dae-11e5-8315-9097e0f08027.png)

So is it the combination of : 
1.
![t](https://cloud.githubusercontent.com/assets/6725097/10358711/e629a06a-6dae-11e5-8585-647b5090f7e2.PNG)
OR is it the combination of :
2.
![tt](https://cloud.githubusercontent.com/assets/6725097/10358715/f0b8fbc0-6dae-11e5-986f-bc977ad53713.PNG)

**Comment by pathumego** [comment]
its the combination 2. Therefore the features are wrong. Lets fix :)

**Comment by pathumego** [comment]
And actually the correct way to show it is  `ට්‍ + ඨ`
