### ISSUE TITLE
Add separate glyphs for YI.post and YIi.post

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#32]
<img width="298" alt="screen shot 2015-10-28 at 6 52 56 pm" src="https://cloud.githubusercontent.com/assets/6846609/10799981/98c2bde4-7da7-11e5-8e21-d2d3f082fa70.png">

**Comment by paarandika** [comment]
Added features and updated GOADB

**Comment by pathumego** [comment]
So now just have to add glyphs?

On Thu, Nov 5, 2015, 9:01 AM Ayantha Randika <notifications@github.com>
wrote:

> Added features and updated GOADB
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mooniak/abhaya-libre-font/issues/32#issuecomment-153994186>
> .
>
-- 

෴ ජය! ෴
පැතුම් එගොඩවත්ත
Pathum Egodawatta
pathum@mooniak.com

**Comment by paarandika** [comment]
yup. And without those glyphs build fails.

**Comment by pathumego** [comment]
What are the glyph names required?

**Comment by paarandika** [comment]
si_Ya.post.MatraI si_Ya.post.MatraI
si_Ya.post.MatraIi si_Ya.post.MatraIi

**Comment by pathumego** [comment]
@kosalaya This is done?

**Comment by pathumego** [comment]
5c706d48c303509363f2bc639caa8fa731f10f87 with this?
