### ISSUE TITLE
Missing Glyphs

### ISSUE THREAD

**Issue by paarandika** [mooniak/abhaya-libre-font#35]
Add si_Ya.post.MatraIi and si_Ya.post.MatraI glyphs.
![yap](https://cloud.githubusercontent.com/assets/6725097/11624186/04f32674-9cf8-11e5-81a6-05e1aa899bcf.PNG)

**Comment by pathumego** [comment]
@paarandika is this same as #32

**Comment by paarandika** [comment]
I think so. Need test to see if its fixed

**Comment by pathumego** [comment]
Done 5c706d48c303509363f2bc639caa8fa731f10f87
