### ISSUE TITLE
Glyph Abnormalities

### ISSUE THREAD

**Issue by paarandika** [mooniak/abhaya-libre-font#36]
It seems that si_Nng.halant and si_Bu are missing in sfd. Please check.
![bu](https://cloud.githubusercontent.com/assets/6725097/11624249/91fd3ffa-9cf8-11e5-98dd-1b4abe01b3dc.PNG)
![hal](https://cloud.githubusercontent.com/assets/6725097/11624250/9200ca6c-9cf8-11e5-9804-d9ba47707885.PNG)

**Comment by pathumego** [comment]
d947fb22f25a7bc812492c10ffd461a4ce071c16
