### ISSUE TITLE
Glyph ".null"

### ISSUE THREAD

**Issue by davelab6** [mooniak/abhaya-libre-font#37]
Glyph ".null" does not comply conventions. A glyph name may be up to 31 characters in length, must be entirely comprised of characters from the following set: A-Z a-z 0-9 .(period) _(underscore). and must not start with a digit or period. The only exception is the special character ".notdef". "twocents", "a1", and "_" are valid glyph names. "2cents" and ".twocents" are not.

**Comment by pathumego** [comment]
fixed
