### ISSUE TITLE
rendering issue - repaya

### ISSUE THREAD

**Issue by pathnirvana** [mooniak/abhaya-libre-font#39]
conjunct letters with repaya is not rendering correctly.
e.g. ර්‍ත්‍ථ - here the repaya should be above ථ. Instead it is to the left of it
![capture](https://cloud.githubusercontent.com/assets/18088975/14061205/a26171c8-f3a0-11e5-9e69-309870cbae3f.JPG)

iskola potha vs abhaya libre rendering difference

**Comment by paarandika** [comment]
Is this the only instance? Or are there any more issues you have stumbled upon regarding Repaya?

**Comment by paarandika** [comment]
Give us few days. We will correct the issue with this.

**Comment by pathnirvana** [comment]
This is one of the common instances. Do try to make your solution more general - i.e. cover all the conjunct letters. ත, ක and න

**Comment by pathumego** [comment]
@kosalaya Talk to @paarandika  about this, we need some help here.

**Comment by pathumego** [comment]
@pathnirvana Can you list the strings for us to test? That will be really helpful for all our projects.

**Comment by pathnirvana** [comment]
will generate some strings and send them over. it would not be exhaustive, but would cover all the cases I know of

**Comment by pathnirvana** [comment]
I have written a small script to generate all the special conjunct glyphs with and without repaya according to the pali alphabet above.
check the word doc inside the attached zip file (same zip as the other issue)
[test glyphs.zip](https://github.com/mooniak/abhaya-libre-font/files/191018/test.glyphs.zip)

**Comment by paarandika** [comment]
I have studied the glyph set. Almost all of them are not in the OpenType specification for Sinhala script. Some of them can be implemented in to current logic in rules. But others like touch form of "ක‍්ෂ්‍යෝ" cannot be implemented in to the current system.

**Comment by pathumego** [comment]
@pathnirvana But all these occur in Pali texts ryt?

**Comment by pathnirvana** [comment]
@paarandika the touching form ක‍්ෂ්‍යෝ is already working fine.
@pathumego the conjunct forms all occur in pali. some of the touching forms might not occur.

**Comment by paarandika** [comment]
![rep](https://cloud.githubusercontent.com/assets/6725097/14102767/30176cc8-f5ba-11e5-8398-03fb7102011b.PNG)
This is the rendering of that touching form in my machine using Abhaya. Is it correct?

**Comment by pathumego** [comment]
@paarandika Touching is supposed to touch I guess @pathnirvana

**Comment by pathnirvana** [comment]
Hmm, it is touching for me in Word 2013
![capture](https://cloud.githubusercontent.com/assets/18088975/14103621/a3fdd3bc-f5be-11e5-8b40-7dfa5fa9b167.JPG)

**Comment by pathnirvana** [comment]
![capture](https://cloud.githubusercontent.com/assets/18088975/14103795/65166bb8-f5bf-11e5-974f-48828c11194f.JPG)

**Comment by pathumego** [comment]
@pathnirvana This is Abhaya Libre on which platform and software version? :) it helps to track the problem

**Comment by paarandika** [comment]
@pathnirvana Can you specify the character(key) sequence for above touching?

**Comment by pathnirvana** [comment]
Windows 10, word 2013.

for touching - zwj + al
for conjunct - al + zwj
between the characters.

**Comment by lianghai** [comment]
@paarandika's Word doesn't reorder the glyphs properly (the syllabification work is wrong). Please use Chrome (HarfBuzz) for such reference.
There're two issues:
1. Sometimes repaya lacks mark positioning on base glyphs (ත්‍ථ, ක්‍ෂ, etc). You need to finish these mark positioning cases.
2. Sometimes repaya is ligated to the base glyphs while the result ligature lacks the left-side cursive positionting anchor, therefore the "touching" mechanism fails. So you just need to add the anchor.

**Comment by davelab6** [comment]
> Please use Chrome (HarfBuzz) for such reference and testing.

Please test on Chrome, Firefox and Safari latest versions - these are primarily web fonts and if they work on the web but not in Word/Adobe, that is regrettable but not a priority for me.

**Comment by pathumego** [comment]
@paarandika whats the status of this. @kosalaya added some glyphs I can see on commit. Can we get the fixes for ttf release ?

**Comment by pathumego** [comment]
@pathnirvana We have fixed some combinations in the v1.050. If you are interested please feel free to send a PR with more features to enable rest of the combinations.

**Comment by pathnirvana** [comment]
@pathumego I will check it out. Many thanks for adding them

**Comment by pathumego** [comment]
@pathnirvana Fixed everything and tested against the strings you provided.
