### ISSUE TITLE
pali special character missing

### ISSUE THREAD

**Issue by pathnirvana** [mooniak/abhaya-libre-font#40]
We are using this font to render our plai tripitaka books and website.
It would be great to have support for these glyphs
![capture](https://cloud.githubusercontent.com/assets/18088975/14061232/2e70a094-f3a1-11e5-842a-46fd5b9f3b1b.JPG)

ට් + zwj + ඨ

**Comment by pathnirvana** [comment]
Attaching the pali alphabet here for your reference.
When we are typesetting old pali books, these come up all the time. It is unfortunate that non of the sinhala fonts support them right now. I wish Abhaya Libre would be able to fill the need.
Many merits to all who are working on this.
![pali alphabet](https://cloud.githubusercontent.com/assets/18088975/14061588/bf70c95e-f3a9-11e5-9697-939b23d62638.jpg)

**Comment by paarandika** [comment]
I just checked. We have the letter in the font and it should render properly. Doing rebuild now to test.

**Comment by pathumego** [comment]
@pathnirvana Thanks a lot for this report! We need some help with making a set of tests for Pali text in Sinhala. We need some standard text strings to test rendering of all the characters properly. Is this something you can help with?

**Comment by pathnirvana** [comment]
will do.

**Comment by pathnirvana** [comment]
I have written a small script to generate all the special conjunct glyphs with and without repaya according to the pali alphabet above.
check the word doc inside the attached zip file

[test glyphs.zip](https://github.com/mooniak/abhaya-libre-font/files/191017/test.glyphs.zip)

**Comment by lianghai** [comment]
@paarandika: In the latest release (https://github.com/mooniak/abhaya-libre-font/releases/tag/1.030), the rule of forming `si_TtTtha` is wrongly coded as `sub si_Tta si_Halant zwj si_Tha by si_TtTtha;` (note the `si_Tha` instead of `si_Ttha` here). This mistake has been corrected in https://github.com/mooniak/abhaya-libre-font/blob/master/features/features.fea but hasn't been reflected in releases yet.

**Comment by paarandika** [comment]
Thanks @lianghai
I also spotted the issue. Im waiting to do another release till we decide on other issues @pathnirvana mentioned.

**Comment by pathumego** [comment]
@paarandika whats the status of this. @kosalaya added some glyphs I can see on commit. Can we get the fixes for ttf release? This is fixed in the 5a27caf31d019a7efe8990ac8656dfaafbfb0164
