### ISSUE TITLE
Preview image inline in README

### ISSUE THREAD

**Issue by davelab6** [mooniak/abhaya-libre-font#42]
Similar to https://github.com/vaishnavimurthy/Akaya-Telivigala/ it would be great to have a PNG image showing a preview of the design, stored in `/documentation/sample.png`, and shown inline in README.md

**Comment by pathumego** [comment]
@kosalaya Can you add sample image to the repo?

**Comment by pathumego** [comment]
@kosalaya Its a good practice to refer to the commit that closes the issue :) You can do that in the commit message or simply provide a link 4e0ea34b785f733eb18d46eea8aab858f7126ff3
