### ISSUE TITLE
Abhaya libre getting bitmapped in PDF generation

### ISSUE THREAD

**Issue by pathnirvana** [mooniak/abhaya-libre-font#44]
When generating a PDF from a word document the libre font gets betmapped while UN-Abhaya is getting embedded correctly.
Zoom the attached PDF and see. First line is UN-Abhaya and second line Abhaya-Libre
Word 2013, Win 10
[generated pdf.pdf](https://github.com/mooniak/abhaya-libre-font/files/365381/generated.pdf.pdf)
![capture](https://cloud.githubusercontent.com/assets/18088975/16866636/a36b21b8-4a8a-11e6-9107-101f1964b1b6.JPG)

**Comment by paarandika** [comment]
It appears that MS word cant embed .otf fonts into PDF files. Is UN-Abhaya a .ttf file?

**Comment by pathnirvana** [comment]
yes it is.

**Comment by pathnirvana** [comment]
The un- font list can be obtained from here 
http://pathnirvana.org/custom/unicode_tools/create_unicode.htm

**Comment by paarandika** [comment]
Yes. Its a ttf font. Thats why it's get embedded. We are currently fixing Abhaya ttf fonts. You can use them afterwards.

**Comment by pathumego** [comment]
@pathnirvana Grab the latest ttf release for embedding  https://github.com/mooniak/abhaya-libre-font/releases/tag/1.050
