### ISSUE TITLE
 Regular Font Error

### ISSUE THREAD

**Issue by Vihangasamaradiwakara** [mooniak/abhaya-libre-font#47]
Bold, ExtraBold, Medium and semiBold is work but Regular Font is not work on Inkscape and Gimp 2.8 !!
![vlcshots2016-12-17-13h43m15s746](https://cloud.githubusercontent.com/assets/15066293/21285447/eaf79c7a-c45e-11e6-9caa-b14e0608c445.jpg)

**Comment by pathumego** [comment]
Could not reproduce. @Vihangasamaradiwakara I think this is a cache issue.
