### ISSUE TITLE
Implement additional ligated conjuncts

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#52]
[EDITED]

12 ligated conjuncts are already included in Abhaya Libre. Some of them are common and few are rare. Few sources [1] [2] [3] have confirmed that the following combinations are ligated in certain Pali and Sanskrit texts. 5–8 needs further confirmation and more sources. We have to look at original sources and research before designing typographic forms. 

<google-sheets-html-origin>

&nbsp; | GLYPH | NON-LIGATED | PHONETIC | CODE POINT SEQUENCE | Notes
-- | -- | -- | -- | -- | --
1 | ඤ්‍ච | ඤ්ච | ny.ca | 0DA4 nya, 0DCA al-lakuna, 200D ZWJ, 0DA0 ca | (DONE 5b47d93) Typographic form is Ca with Sannyaka stroke. DONE 5b47d93
2 | ඤ්‍ඡ | ඤ්ඡ | ny.cha | 0DA4 nya, 0DCA al-lakuna, 200D ZWJ, 0DA1 cha | (DONE 5b47d93) Typographic form is Cha with Sannyaka stroke 
3 | ච්‍ච | ච්ච | c.ca | 0DA0 ca, 0DCA al-lakuna, 200D ZWJ, 0DA0 ca | (DONE 8103767dbd841e902dcc73fcd57c6eafb13a44c4 )(Pali Chayanna - පාලි චයන්න) #58
4 | බ්‍බ | බ්බ | b.ba | 0DB6 ba, 0DCA al-lakuna, 200D ZWJ, 0DB6 ba |  (DONE 5b47d93) Sabba Bayanna - සබ්බ බයන්න #54 
5 | ණ්‍ඩ | ණ්ඩ | nn.dda | 0DAB nna, 0DCA al-lakuna, 200D ZWJ, 0DA9 dda | (DONE 5b47d93) Typographic form is ඬ
6 | ඤ්‍ජ | ඤ්ජ | ny.ja | 0DA4 nya, 0DCA al-lakuna, 200D ZWJ, 0DA2 ja |  (DONE 5b47d93) Typographic form is ඦ
7 | ම්‍බ | ම්බ | mb.ba | 0DB8 ma, 0DCA al-lakuna, 200D ZWJ, 0DB6 ba |  (DONE 5b47d93) Typographic form is ඹ
8 | ඞ්‍ග | ඞ්ග | ng.ga | 0D9E nga, 0DCA al-lakuna, 200D ZWJ, 0D9C ga |  (DONE 5b47d93) Typographic form is ඟ)
</google-sheets-html-origin>

Tracking these on this [spreadsheet](https://docs.google.com/spreadsheets/d/10hgjIq7U7VAX2RsRq0q5AnyDFw-yKGdx3GE8UbwLH4c/edit?usp=sharing).

These should be implemented with the same strategy used to  invoke (`<al-lakuna, ZWJ>`) the existing ligated conjuncts. 

Additionally it would be nice to implement a [OpenType stylistic set](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-ss01---ss20) feature so users can invoke these ligatures even if the text is not encoded to ligate the conjuncts. Tracking this here >> #56

***    

[1] Page 57 from  තියඩෝර් ජී ගුරුන්නාන්සේගේ ව්‍යාකරණ පොත >> (TODO Get the title page and exact details)

![186544430_1536103543447664_3854911375201684958_n](https://user-images.githubusercontent.com/6846609/119914855-d7aa9f80-bf7e-11eb-9ce8-b83d83d167b0.jpeg)

[2] @pathnirvana provided this image in #39 taken from  Buddha Jayanthi Tipitaka. But this identifies the above 1.
![bf70c95e-f3a9-11e5-9697-939b23d62638](https://user-images.githubusercontent.com/6846609/119928287-ea31d280-bf98-11eb-9d84-952d778c3787.jpeg)

[3] https://pitaka.lk/tools/unicode/pali_bandi.htm#id-UN-Abhaya

**Comment by pathumego** [comment]
@pathnirvana Yes! I am aware of the UN fonts. We want to make sure Abhaya Libre supports all needed ligatures for Pali, including the edge cases and rare ligatures. If you see anything to add here please do. Would love to have you onboard for testing.

**Comment by bgliyanage** [comment]
For providing solid evidence for numbers 5 and 8, I hereby add photos of an ola leaf book. Photo courtesy to venerable Sangha of Peliyagoda Vidyalankara Pirivena. Here someone can see, කුම්භණ්ඩ and මඞ්ගල. 
![kumbhanda](https://user-images.githubusercontent.com/85128519/120232164-9eb94600-c270-11eb-9672-6925f9689078.jpg) 
![mangala](https://user-images.githubusercontent.com/85128519/120232188-aa0c7180-c270-11eb-88da-1e21d7c6ab95.jpg)

**Comment by pathumego** [comment]
@bgliyanage provided a list of words for each conjunct for testing purposes. Uploaded [here](https://github.com/akuru/sinhala-font-tools/blob/gh-pages/test-documents/pali-and-sanskrit-words.md)

**Comment by pathumego** [comment]
@bgliyanage @JanakaCB Please take a look >>
[abhaya_libre_ligated_conjuncts.pdf](https://github.com/mooniak/abhaya-libre-font/files/6604006/abhaya_libre_ligated_conjuncts.pdf)

**Comment by bgliyanage** [comment]
Great job, Pathum. Now the reformation is 90% complete. Still we need to consider designing ච්ච conjunct and making three or more glyph conjuncts. Best wishes to all.

**Comment by pathumego** [comment]
All these conjuncts are added. There is one more we are tracking in #61. Not including in this list as we might be using a different strategy to encode it.
