### ISSUE TITLE
Add 'බ්බ සංයෝගය' (b.ba ligated conjunct)

### ISSUE THREAD

**Issue by JanakaCB** [mooniak/abhaya-libre-font#54]
Sabba Bayanna is the combination of බ්බ glyphs and it is frequently used in Pail texts. See the below reference images scanned from early letterpress printed book "නාමමාලා හෙවත් නාම වරනැගිල්ල" by වස්කඩුවේ සුභූති හිමි in 1876 CE. (Image Courtesy to Mr. Bertram Liyanage)

![1](https://user-images.githubusercontent.com/13979985/119923123-cb2e4300-bf8e-11eb-97c4-707069a1cae7.jpg)

![2](https://user-images.githubusercontent.com/13979985/119923169-d97c5f00-bf8e-11eb-9687-31609a2d8f21.jpg)

And one example for the intended usage (of proposed glyph) is shown below as an image. (Image Courtesy to Author) The phrase in it is "සබ්බීතියෝ විවජ්ජන්තු සබ්බරෝගෝ විනස්සතු..."

![Screenshot 2021-05-27 214409](https://user-images.githubusercontent.com/13979985/119921165-2bbb8100-bf8b-11eb-8f9b-896bc30d6809.jpg)

**Comment by pathumego** [comment]
@JanakaCB Can you provide details about these sources? It is better to document these things properly.

**Comment by JanakaCB** [comment]
> @JanakaCB Can you provide details about these sources? It is better to document these things properly.

Edited and Added. The book is "නාමමාලා හෙවත් නාම වරනැගිල්ල" by වස්කඩුවේ සුභූති හිමි in 1876 CE.

**Comment by kosalaya** [comment]
What is the possibility of making this point more in line with this curve in letter 'ම'?
![119921165-2bbb8100-bf8b-11eb-8f9b-896bc30d6809](https://user-images.githubusercontent.com/8073976/120105033-f70b1d80-c174-11eb-8dbb-89deb7d1ead6.jpeg)
<img width="580" alt="Screenshot 2021-05-30 at 18 26 29" src="https://user-images.githubusercontent.com/8073976/120105039-fc686800-c174-11eb-8147-e2c93af2eefc.png">

**Comment by JanakaCB** [comment]
I think it should be in-lined with the earlier form of letter 'බ'. See below screenshots taken from the first movable letterpress printed Sinhala book (Singaleesch Gebeede-Boek -1737) for details.

![Screenshot 2021-05-30 194035](https://user-images.githubusercontent.com/13979985/120113082-7bba6380-c196-11eb-86da-0b820f027c4b.jpg)

![Screenshot 2021-05-30 162733](https://user-images.githubusercontent.com/13979985/120113083-7bba6380-c196-11eb-8e6c-8fc548a7950e.jpg)

The continuous curve we see in the contemporary 'බ' is not seen there, and moreover it's a pointed curve. 
Hence, the form with the pointed curve should be the earlier form of this letter, specifically at the beginning era of  Sinhala printing. And as this letter 'Sabba Bayanna' also comes from that era, I think the pointed curve fits better there.

**Comment by bgliyanage** [comment]
Here I'll provide some solid evidence from 80 years ola-leaf book. Photo courtesy to venerable Sangha of Peliyagoda Vidyalankara Pirivena. Here someone can see බ්බො, ගන්ධබ්බො, ගන්ධබ්බි, සබ්බේ in these pictures. 
![pubbo](https://user-images.githubusercontent.com/85128519/120231383-eccd4a00-c26e-11eb-9c6d-80b2e3309f56.jpg) 
![gandhabba](https://user-images.githubusercontent.com/85128519/120231396-f6ef4880-c26e-11eb-958e-f64d7df20220.jpg) 
![sabbe](https://user-images.githubusercontent.com/85128519/120231413-ff478380-c26e-11eb-87df-c73bb890829c.jpg)

**Comment by bgliyanage** [comment]
Here again, I suggest going with බ්බ සංයෝගය instead of sabba bayanna, which is more readable and meaningful for the Sinhala audience.

**Comment by JanakaCB** [comment]
> solid evidence

Couldn't agree more. It's conclusive evidence for the validity of pointed curve.

**Comment by JanakaCB** [comment]
Cannot add the sfd file of the designed glyph due to the GitHub restriction; _"We don’t support that file type. Try again with a GIF, JPEG, JPG, MOV, MP4, PNG, CSV, DOCX, FODG, FODP, FODS, FODT, GZ, LOG, MD, ODF, ODG, ODP, ODS, ODT, PDF, PPTX, TXT, XLS, XLSX or ZIP."_

Hence, I'm adding the file to Google Drive and share the link here. 

https://drive.google.com/file/d/1-UF2nNeioifIirTRg0fIZHCRa01tClxX/view?usp=sharing

**Comment by pathumego** [comment]
I designed two options based on @JanakaCB s proposal; one with the sharp pointed turn and one with a turn similar to that of _ba_ and _ma_. @JanakaCB @bgliyanage Thoughts?

<img width="735" alt="Screen Shot 2021-06-06 at 1 07 05 PM" src="https://user-images.githubusercontent.com/6846609/120916599-1f8c9d80-c6c8-11eb-9bd0-5826619d9ace.png">

**Comment by bgliyanage** [comment]
I prefer option 2 to the first one, for the curved point is the salient feature to distinguish it from ඞ  in printed glyph.

**Comment by pathumego** [comment]
I agree too. I wanted to explore the shapes. I will go ahead and implement this.

**Comment by pathumego** [comment]
<img width="1134" alt="Screen Shot 2021-06-06 at 3 23 01 PM" src="https://user-images.githubusercontent.com/6846609/120920170-27a20880-c6db-11eb-9738-04618dd40529.png">

**Comment by pathumego** [comment]
DONE 5b47d93
