### ISSUE TITLE
U and Uu subscript forms

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#55]
When followed by Rakar U and Uu signs take a subscript form.

This is document prepared by [Kalum Bandara ](https://www.facebook.com/matalekalum)

<img width="815" alt="Screen Shot 2021-05-28 at 8 11 26 AM" src="https://user-images.githubusercontent.com/6846609/119921955-84d7e480-bf8c-11eb-946b-64f52d8fc83a.png">

[letter.pdf](https://github.com/mooniak/abhaya-libre-font/files/6557807/letter.pdf)

**Comment by pathumego** [comment]
DONE :) 

<img width="1580" alt="Screen Shot 2021-05-28 at 9 19 52 AM" src="https://user-images.githubusercontent.com/6846609/119926912-f36d7000-bf95-11eb-9361-b248c22a3e1f.png">

**Comment by pathumego** [comment]
Waiting for Kalum to confirm.

**Comment by Kallum-Bandara** [comment]
Well done! This is how exactly it should be. I really appreciate your grate contribution for the correct use of Sinhala language.

**Comment by pathumego** [comment]
@Kallum-Bandara Welcome and thanks!

**Comment by pathumego** [comment]
Posting test words for future reference. 
ධ්‍රුවය
ක්‍රූර
බ්‍රූහි
ජනශ්‍රුතිය
භ්‍රූණයින්
ශ්‍රුතමය
කල්පද්‍රුමය
