### ISSUE TITLE
Explore stylistic set OT features for ligated conjuncts and Pali texts 

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#56]
We can enable a OpenType Stylistic Set feature to invoke ligatures used for Pali texts even if the text is not encoded ’properly’ (ligated conjuncts are encoded with `<al-lakuna zwj>`).  This feature can be named `Ligatures for Pali texts` and will invoke all the provided ligated conjuncts without the need to have `zwj` in the sequence.  
  
NOTE: In addition to ligated conjuncts when writing Pali in Sinhala al-lakuna is omitted. Should we do that as well in OT features?

PROS;
This will allow users to access and use the ligated conjunct glyphs without needing to encode text with zwj. Which is useful since most platforms still do not handle zwj well. 

CONS
This will allow users to display Pali texts ’properly’, but with ’incorrect’ encoding. We should always encourage users to correctly encode their text.

**Comment by bgliyanage** [comment]
I like to supplement something to your note on the hal-lakuna. In transliterating Pali and Sanskrit in Sinhala characters, there are only two possible styles; (1) using conjunct letters in place of hal-lakuna and (2) using hal-lakuna without conjunct letters. Writing conjunct letters along with hal-lakuna is illogical and absurd also. Therefore, it is not difficult to make a sharp demarcation between these two styles.

**Comment by pathumego** [comment]
Implementing this will only add confusion as it is a ’hacked encoding‘. We have to encourage correct encoding instead
