### ISSUE TITLE
Ligatures and OT features 

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#57]
Need to make a proper classification of alternates, ligatures and other forms and develop a standard for which OT tags to use for each class, so that  all our fonts—and hopefully other Sinhala fonts from various vendors—can have a uniform way to invoke these ligatures. 

Following is the current feature layout.

-  `dlig` = Sinhala Da-forms subscripts
-  `ss01`= Sinhala Da-forms subscripts (for backwards compatibility with v01)
- `ss02` = Sinhala fPa (alternate form of Fa)
- `ss03`= Sinhala Archaic ligatures 
- `ss07`= Sinhala Lith Numerals
- `ss08`= Sinhala Archaic Numerals

**Comment by ravincaldera** [comment]
![alternatives](https://user-images.githubusercontent.com/58606701/122153914-8a389880-ce81-11eb-89b4-5869bf9eb620.png)

**Comment by pathumego** [comment]
@ravincaldera these are stylistic decisions and dose not need an encoding level representation. In Abhya Libre these alternate forms are included as Discretionary Ligatures `dlig` and also as Stylistic Set 01 `ss01` You can see how to enable these on [various software here](https://www.youtube.com/watch?v=CjOoRyMypN8&t=26s&ab_channel=AkuruCollective). On LibreOffice [here](https://www.youtube.com/watch?v=y1d7gHOLWZA&ab_channel=HaraldGeisler)
