### ISSUE TITLE
Add 'ච්ච සංයෝගය' (c.ca ligated conjunct)

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#58]
Implement  ච්ච (c.ca) ligated conjunct used in Pali and Sanskrit texts. Have to further investigate the sources and decide on the typographic form. Sequence is `0DA0 ca, 0DCA al-lakuna, 200D ZWJ, 0DA0 ca`

**Comment by JanakaCB** [comment]
See this, as seen in the image "සංයෝග චකාරය" is "පාලි චයන්න". The reference book is "නාමමාලා හෙවත් නාම වරනැගිල්ල" by වස්කඩුවේ සුභූති හිමි in 1876 CE.

![Screenshot 2021-05-30 150724](https://user-images.githubusercontent.com/13979985/120100449-6c1f2880-c15e-11eb-89e3-c78f9b7446a1.jpg)

**Comment by bgliyanage** [comment]
Let me give some solid evidence. These pictures are taken from some 80 years old ola-leaf book. Photo credit goes to the venerable sangha of Peliyagoda Vidyalankara Pirivena. In these pictures, someone can easily trace the words,  සච්ච, and සච්චෙන. 
![sacca](https://user-images.githubusercontent.com/85128519/120229063-ff915000-c269-11eb-98c1-d6bdd8ff1358.jpg) 
![saccena](https://user-images.githubusercontent.com/85128519/120229094-0d46d580-c26a-11eb-97a2-d7f17bd2bcca.jpg) 
![saccena 2](https://user-images.githubusercontent.com/85128519/120229114-19cb2e00-c26a-11eb-998a-691e1208da77.jpg)

**Comment by bgliyanage** [comment]
With all respect, I'm here going to make a case that your term පාලි චයන්න is not a good coinage, for this ligated conjunct ච is in Sanskirt also. I suggest going with ච්ච සංයෝගය which is more meaningful for the Sinhala audience.

**Comment by JanakaCB** [comment]
මේ සම්බන්ධව මුද්‍රිත ලේඛන ඇසුරෙන් ලදහැකි සාක්ෂි අල්පයි. එසේම ඒවායේ සංයෝග චකාරය යැයි පෙන්වා ඇති හැඩයයන් එකිනෙකට පරස්පර බවත් එම හැඩය නිරන්තරයෙන් ඩයන්න සමඟ පටලවාගැනෙන බවත් පෙනේ. එසේම මෙම අකුර සම්බන්ධව බොහෝ විට කෙරෙන්නේ එය ලියවී ඇති සංදර්භය විමසා එය ඩයන්නද චයන්නද යන්න නිශ්චය කරගැනීම බව මේ සම්බන්ධව කෙරුණු විමර්ශනයේදී පැහැදිලිව ඒත්තු ගැන්වී තිබේ. 

එහෙයින් සංයෝග චකාරයේ නියම හැඩය සොයාගැනීම උදෙසා අප යොමුවිය යුත්තේ පුස්කොළ ලේඛන වෙතයි. එහෙත් පුස්කොළ ලේඛන යනු අත්අකුරු වන නිසා එකිනෙකට වෙනස් අත්අකුරු අතර සාම්‍යයක් ගොඩනැංවිය හැකි යම් ක්‍රමවේදයක් අවශ්‍ය වේ. එම සාම්‍යය නම් සංයෝග චයන්න යන අකුර පුස්කොළයේ අතින් ලියූ සහ දැනටමත් ලියන (scribe) අය විසින් ඩයන්න, චයන්න, සහ සංයෝග චයන්න ලිවීමේදී පන්හිඳ හැසිරවීම කෙරෙහි දක්වන එකිනෙකට වෙනස් අභිමතාර්ථය කුමක්ද යන්නයි. එනම් ඔවුන්ගේ විඥානය විසින් සංයෝග ච කාරය අනෙක් අකුරුවලින් වෙනස්බව දැනටමත් දන්නා නිසා එම අකුර ලිවීමේදී පන්හිඳ හැසිරවීමට තුඩුදෙන මානසික ක්‍රියාකාරීත්වය කවර ආකාරයක් ගන්නේද යන්නයි. ඒ බව දැනගැනීම සඳහා පන්හිඳ ඇසුරු කරන, දැනටමත් පුස්කොළයේ ලියන අය කිහිප දෙනෙකුගෙන් සංයෝග චයන්න ලිවීමේදී පන්හිඳ හැසිරවීම සෑම නැම්මක් නැවතුමක් හැරීමක් පාසාම සවිස්තරව වචනයෙන් විස්තර කරන ලෙස ඉල්ලා සිටින ලදී. 

එහිදී පැහැදිලි වූයේ මුල් චයන්න ලියමින් මුල් චයන්නේ පහලට යන වක්‍රයේ පහලම ලක්ෂ්‍යය පසුකර ආපසු ඉහලට හැරෙන විට දෙවන චයන්න ඊට සම්බන්ධ කිරීමට සිතන බවයි. ඒ අනුව දෙවන චයන්නේ පහලට එන වක්‍රයේ පහලම ලක්ෂ්‍යයට පෙර එහෙත් ඊට ආසන්නව පටන්ගන්නා වක්‍ර කොටස මුල් වක්‍රය හා සම්බන්ධ කර (ක්‍රමයෙන් ඉහලට ගෙන ඉදිරියට නවා) අකුර අවසන් කරන ලදී. ඒ අනුව සංයෝග චයන්න අල්පප්‍රාණ චයන්නේ හැඩයට වඩා  පළලින් වැඩි හැඩයක් ගනී. තවද සංයෝග ච අකුරේ පහළ කොටසේ ඇති අල්ප චයනු අකුරු දෙක එකිනෙකට සබඳ වන තැන ඩ යන්නක හෝ ඹ යන්නක මෙන් ප්‍රකටව විශද වන නැම්මක් තිබිය නොහැකිය; එසේ ප්‍රකට වන නැම්මක් යෙදීමෙන් සංයෝග චයන්න ඩයන්න සමඟ පැටලෙන්නට ඉඩ ඇති බව අකුර ලියන්නා දැනටමත් දන්නා හෙයිනි. 

එහෙත් මෙම නැම්මේ ස්වරූපය එක් එක් අය විසින් එකිනෙකට වෙනස් අයුරින් පුස්කොළ පොත්වල ලේඛනගත කර ඇති බවත් නිරීක්ෂණය විය. ඒ අනුව සංයෝග ච හි නැම්ම පිළිබඳව ඒකමතික පොදු එකඟතාවයක් නොතිබුණු බවත් පැහැදිලි විය. 

ලාංකීය ඉතිහාසය විමසන විට, ලේඛණ සම්ප්‍රදායෙන් මුද්‍රණ සම්ප්‍රදායට වන ආගමනයේදී සිදුවූ තාක්ෂණික වෙනස්කම් හමුවේ මුල් වටයෙන්ම භාවිතයෙන් ඉවත්වී ගිය සංයෝගාක්ෂරයක් ලෙස මෙම සංයෝග චයන්න හඳුනාගත හැකිය. එසේ මෙම අකුර භාවිතයෙන් ඉවත්වීම පිටුපස ඇති ප්‍රධානතම හේතුව මෙම අකුරේ හැඩය පිළිබඳව එවකටත් තිබුණු විසඳා නොගත් අවිනිශ්චිත බව බවට අපට පෙනීගොස් තිබේ.

විමර්ෂණයේදී ලැබුණු විස්තර විභාග විශ්ලේෂණය කිරීමෙන් අනතුරුව සංයෝග චයන්න සඳහා අප විසින් යෝජනා කරන හැඩය මෙහි පහලින් අමුණා තිබේ.

![Screenshot 2021-06-08 170952](https://user-images.githubusercontent.com/13979985/121197108-aa1ef980-c88e-11eb-91f6-e18879136a71.jpg)

**Comment by JanakaCB** [comment]
යෝජිත හැඩය සංසන්දනය සඳහා ච, ඩ, ඹ අකුරු හැඩ සමඟ.

![Screenshot 2021-06-08 192544](https://user-images.githubusercontent.com/13979985/121198244-9c1da880-c88f-11eb-9f23-4a1ccd03ff76.jpg)

**Comment by pathumego** [comment]
@JanakaCB ඔබේ යෝජනාව මූලික අදහසක් ලෙස මම පිලිගන්නවා. නමුත් අදහස් කීපයක් එකතු කරන්නම්.

මේ අලුත් අකුර පැරණි පොතපතේ ඇති ලෙස පදනම්ව නිමවන නමුත් අපිට සැලකිය යුතු කාරණා කීපයක් තියෙනවා;

1. පැහැදිලිව අතින් ලිවිය හැකි සහ පහසුවෙන් විවිධ රුවකුරු වලට ගැලපෙන පරිදි සකස්කළ හැකි සැකිල්ලක් හඳුනාගත යුතුයි.
2. අප විසින් භාවිතයට එකඟවන අකුරේ හැඩය අනෙකුත් ආසන්න අකුරු (උදා: ඩ, ඹ, ච) හැඩවලින් වෙන්ව—විශේෂයෙන්ම පුංචි අකුරු ප්‍රමාන (small text size) වලදී— පහසුවෙන් ඇසට හඳුනාගන්නට හැකිවිය යුතුයි.
3. සිංහල මුද්‍රිත අකුරුවල ටයිපොග්‍රැෆිමය රටාවනට (typographic patterns) සහ අභය රුවකුරේ රූපමය රටාවනට (visual patterns) ගැලපෙන හැඩයන් තෝරාගත යුතුයි. අකුරක ටයිපොග්‍රැෆිමය යෙදීම, ලිවීමේ රටාවට වඩා වෙනස් වෙන්නට හැකි බව සිහියේ තබාගැනීමත් වැදගත්. 

මේ කාරණා මත පදනම්ව බැලූවිට ඔබේ යෝජිත අකුර ඒ ලෙසින්ම ගත්තොතින් එය කුඩා ප්‍රමාන වලදී වෙන්කර හඳුනා ගැනීම අපහසු බව පෙනී යනවා 
මේ ’රැල්ල‘ පිලිබඳ අදහස ඉදිරියට ගෙනයා හැකියි. එය වඩා කැපී පෙනෙන ලෙස පෙන්විය යුතු බව සහ අතින් ලියු  ’රැල්ල‘ වෙනුවට  ’ටයිපොග්‍රැෆිමය රැල්ල‘ක් හඳුන්වා දියයුතු බව මගේ අදහසයි. 

මේ අදහස් මත පදනම්ව මම පහත යෝජනා දෙක ඉදිරිපත් කරනවා. (@JanakaCB ගේ යෝජනාව මම යෝජනාව 1 ලෙස සලකනවා.)

***
### යෝජනාව 2

<img width="704" alt="Screen Shot 2021-06-09 at 1 45 38 PM" src="https://user-images.githubusercontent.com/6846609/121318615-0a627980-c929-11eb-8ad3-10fb35cfd386.png">
<img width="750" alt="Screen Shot 2021-06-09 at 1 39 24 PM" src="https://user-images.githubusercontent.com/6846609/121318645-12221e00-c929-11eb-87f7-0ee27d3d655a.png">

***
###  යෝජනාව 3
<img width="725" alt="Screen Shot 2021-06-09 at 1 44 58 PM" src="https://user-images.githubusercontent.com/6846609/121318751-29f9a200-c929-11eb-9fe4-117b1f9055f2.png">
<img width="752" alt="Screen Shot 2021-06-09 at 1 40 25 PM" src="https://user-images.githubusercontent.com/6846609/121318764-2d8d2900-c929-11eb-893a-bc35ed27afcd.png">

**Comment by JanakaCB** [comment]
Just for the record:

ඉහත මවිසින් යෝජනා කළ (පැතුම් අංකනය කර ඇති පරිදි "යෝජනාව 1") හි ඇති නිර්මාණය කෙරේ එළඹීමට පාදක වූ වස්කඩුවේ සුභූති හිමියන්ගේ නාමමාලා හෙවත් නාම වරනැගිල්ල (ව්‍ය.ව. 1876) ග්‍රන්ථයේ ස්කෑන් කරන ලද පිටපත් භාවිතයෙන් කරන ලද විශ්ලේෂණය මෙහි අමුණා තබමි. සංයෝග චයන්නේ ද්විවක්‍ර සන්ධිය සමඟ ස ය ඩ ඪ ද්‍ධ අකුරුවල ද්විවක්‍ර සන්ධි යෙදෙන ආකාරය එකට තබා විමසූ හැටි එහි අඩංගුව ඇත. (ඹ යන්නද අවසානයට ඇත) විශාලනය කර අකුරු එකිනෙක සසඳා බලන්න. 


![CCA](https://user-images.githubusercontent.com/13979985/121350193-fbd78a80-c947-11eb-8015-1941a830ff62.jpg)

**Comment by JanakaCB** [comment]
@pathumego ඔබගේ කොමෙන්ටුවේ අංක 1, 2,3 යටතේ පෙන්වාදී ඇති කරුණු වලට එකඟයි. ඒ සියල්ල සළකා බැලූවිට මෙහි යෝජිත නිර්මාණ ආකාර තුන අතරින් යෝජනාව 2 ලෙස සඳහන් නිර්මාණය වඩාත් සුදුසු බව පෙනේ. තවද එය අපගේ මුද්‍රිත ලේඛන මූලාශ්‍රය හෙවත් නාමමාලාවෙහි ඇති ච්ච සංයෝගාක්ෂරයේ හැඩයට ඉතා ආසන්න හැඩයක් ගන්නා බවත් නිරීක්ෂණය කළ හැකිය.

**Comment by JanakaCB** [comment]
ච්ච සංයෝගාක්ෂරය පිළිබඳව කළ විමර්ශනයේදී හමුවූ විලේගොඩ සිරිවිමල හිමියන් විසින් රචිත 'ලක්දිව පුස්කොළ පොත්වල අක්ෂර පිළිබඳ හැඳින්වීමක්' ලිපියේ pdf පිටපත මෙහි එක්කරමි. ච්ච සංයෝගාක්ෂරය පුස්කොළ පොත්වල ලියැවී ඇති ආකාරය පිළිබඳව එහිදී කරුණු විමසා තිබේ. 
එම පිටපත අපවෙත ලබාදුන් ශකිල රාජකරුණා මහතාට ස්තුතිවන්ත වෙමි. 

[විලේගොඩ සිරිවිමල හිමි.pdf](https://github.com/mooniak/abhaya-libre-font/files/6625566/default.pdf)

**Comment by pathumego** [comment]
***
###  යෝජනාව 4

<img width="691" alt="Screen Shot 2021-06-10 at 9 16 21 AM" src="https://user-images.githubusercontent.com/6846609/121461862-49e2a180-c9cd-11eb-8d81-b5cfa7ed0da6.png">
<img width="699" alt="Screen Shot 2021-06-10 at 9 16 10 AM" src="https://user-images.githubusercontent.com/6846609/121461870-4e0ebf00-c9cd-11eb-8eaf-9761ba33c66a.png">
<img width="882" alt="Screen Shot 2021-06-10 at 9 16 37 AM" src="https://user-images.githubusercontent.com/6846609/121461878-51a24600-c9cd-11eb-93d8-94e1cbd395ca.png">

**Comment by pathumego** [comment]
***
###  යෝජනාව 5

<img width="665" alt="Screen Shot 2021-06-10 at 10 05 56 AM" src="https://user-images.githubusercontent.com/6846609/121465500-8dd8a500-c9d3-11eb-85bb-d59eed981663.png">
<img width="704" alt="Screen Shot 2021-06-10 at 10 05 50 AM" src="https://user-images.githubusercontent.com/6846609/121465505-90d39580-c9d3-11eb-8e3e-366c96650f1e.png">
<img width="899" alt="Screen Shot 2021-06-10 at 10 06 14 AM" src="https://user-images.githubusercontent.com/6846609/121465516-93ce8600-c9d3-11eb-9355-61fa27e811f1.png">

**Comment by ravincaldera** [comment]
ඔබගේ කණ්ඩායම විසින් කළ “ව්ච” සංගෝගය පිළිබඳ සාකච්ඡාවට ඇහුම්කම් දුනිමි. ඔබගේ කණ්ඩායම විසින් වැළලී ගිය අකුරක් හා බැදි අක්ෂර නිර්මාණය කිරීම පිළිබඳ මගේ කෘතඥතාවය පළ කරන්නට කැමැත්තෙමි. බැඳි අකුරු පිළිබඳ කථිකාවේදී සාකච්ඡා කළ අකුරු සියල්ල ම පිළිබඳ මාගේ පෞද්ගලික අකුරු නිර්මාණයන්ට ඇතුලත් කිරීමට උත්සහ ගතිමි. එහෙත් පවතින ගැටලුව වන්නේ එකී අකුරු ලේඛනයට ගැනීම සඳහා කේතනය කළ හැකි ක්‍රමවේදයන් පිළිබඳ  ද සාකච්ඡාවට ගත යුතු ය. ඔබගේ යෝජනාව මෙන් ඩ වඩා පළලින් යුක්තව, තුළ මදක් ඉස්සුනු ස්වරූපය මගේ අදහස අනුව සුදුසුයයි මම සිතමි. 
අකුරු සඳහා කේතනය කවරා කාර ද?
![Akuru](https://user-images.githubusercontent.com/58606701/121564741-6ddbcc80-ca39-11eb-8799-4ef5ca0940c0.png)

**Comment by bgliyanage** [comment]
සඤ්ඤක ශ සම්බන්ධයෙන් මා යෙදූ සටහන කරු. බලන්න.

**Comment by JanakaCB** [comment]
අකුරු එකතුවේ Youtube නාලිකාවට එක්කර ඇති ( https://www.youtube.com/watch?v=hJLsKcfZUy4 ) අපගේ online සාකච්ඡාවේදී බර්ට්‍රම් ලියනගේ මහත්මයා විසින් සඳහන් කරන ලද පරිදි පුස්කොළ මූලාශ්‍රය හා සැස‌‌ඳෙන නිර්මාණයක් සිදුකිරීමේ අවශ්‍යතාවයට ප්‍රමුඛත්වය දෙමින් නිර්මාණය කළ ච්ච සංයෝගාක්ෂරය සඳහා යෝජිත මෙම හැඩය යෝජනාව 6 ලෙස එක්කරමි. 

**යෝජනාව 6**

![Screenshot 2021-06-09 185845](https://user-images.githubusercontent.com/13979985/121585438-362c4f00-ca50-11eb-8eb8-842b96bed235.jpg)

**Comment by pathumego** [comment]
> අකුරු සඳහා කේතනය කවරා කාර ද?

@ravincaldera  OpenType සිංහල සම්මතය ග්‍රහණක්ෂර (fused conjuncts) සහ බන්ධක්ෂර (touching conjuncts ) කේතනය කරන්නේ දෙවිදිහකට. ඒ පිලිවෙලින්  <0DCA al-lakuna, 200D ZWJ> සහ  <200D ZWJ, 0DCA al-lakuna> මගින්.

<img width="1417" alt="Screen Shot 2021-06-11 at 9 49 01 AM" src="https://user-images.githubusercontent.com/6846609/121630691-43baf680-ca9b-11eb-8223-c3b511e2b880.png">
රූපය අභය ලිබ්‍රේ රුවකුරින්


මේ අනුව ඔබට පෙනෙනවා ඇති ඔබ ඉදිරිපත් කර ඇති රූපයේ `බ touch බ` සහ `ච touch ච` කේතනය වැරදි බව සහ පැටලීමකින් තොරව මේ දෙක වෙන් වෙනම කේතනය කල හැකි බව. සඤ්ඤක ශ ගැන මම මෙතන  https://github.com/mooniak/abhaya-libre-font/issues/61#issuecomment-859248963 සටහන් කළා.

**Comment by ravincaldera** [comment]
ඔබගේ පැහැදිලි කිරීම ගැන ස්තූතියි. මෙය බැඳි අකුරු පිළිබඳ සාකච්ඡාවේදී ද පැහැදිලි කර තිබුණි. එහෙත් ඔබ විසින් දැක්වූ ආකාරකයට Windows සහ MS Wordවල අභය ලිබ්‍රේ රුවකුර ක්‍රියාත්මක වන්නේ  නැත. එය මා භාවිත කරන Sinhala–Wij 9 Keyboard නිසා වන්නේ දැයි නොදනිමි. එහි ක්‍රියාත්මක වන්නේ  පහත අකාරයට ය:

ද් + ධ  → ද්ධ   (ක්‍රියාත්මකයි)
ද + zwj + ධ  →  ද්‍ධ (ද+්+ zwj+ධ [ ඔබ දක්වා ඇති පිළිවලට ක්‍රියාත්මක නොවේ] ) 
ද + zwj+ ් + ධ  → ද්‍්ධ (ක්‍රියාත්මක නොවේ)

මේ පිළිබඳ යම් පැහැදිලි කරන්නේ නම් මම කෘතඥ වෙමි෴

**Comment by ravincaldera** [comment]
![Akuru](https://user-images.githubusercontent.com/58606701/121635657-4110cf00-caa4-11eb-8e81-e412dcd0968a.png)
අභය ලිබ්රේ ුවකුරෙන්

**Comment by pathumego** [comment]
@ravincaldera කරුණාකර මේ ගැන සාකච්ඡාවට වෙනම Issue එකක් open කරන්න හැකි ද? මෙතනට අදාළ නැහැ නේ. මම එතන පැහැදිලි කරන්නම්.

**Comment by ravincaldera** [comment]
> @ravincaldera කරුණාකර මේ ගැන සාකච්ඡාවට වෙනම Issue එකක් open කරන්න හැකි ද? මෙතනට අදාළ නැහැ නේ. මම එතන පැහැදිලි කරන්නම්.
ඔබ කී පරිදි  new Issue එකක් විවෘත කළා #66. මෙම පිටුවෙන් අනවශ්‍ය සාකච්ඡාව ඉවත් කළා. ස්තූතියි.

**Comment by pathumego** [comment]
@JanakaCB ගේ යෝජනාව 6 පහත පරිදි සකස් කළා.

<img width="1265" alt="Screen Shot 2021-06-11 at 11 44 40 AM" src="https://user-images.githubusercontent.com/6846609/121649303-1465b300-cab6-11eb-8054-58b3712e6aab.png">
<img width="1214" alt="Screen Shot 2021-06-11 at 11 43 17 AM" src="https://user-images.githubusercontent.com/6846609/121649319-1891d080-cab6-11eb-8394-460c72899048.png">
<img width="1268" alt="Screen Shot 2021-06-11 at 11 44 21 AM" src="https://user-images.githubusercontent.com/6846609/121649390-26475600-cab6-11eb-8da7-e11e44e78c57.png">

**Comment by pathumego** [comment]
යෝජනාව 6 අභය ලිබ්‍රේ රුවකුරට එක්කරන ලදි. 

<img width="1154" alt="Screen Shot 2021-06-11 at 1 31 54 PM" src="https://user-images.githubusercontent.com/6846609/121652569-68be6200-cab9-11eb-86c1-b380493f6958.png">

**Comment by pathumego** [comment]
පහත text එක copy කරගෙන උත්සහ කරන්න. ඔබ ටයිප් කරන විදිහේ අවුලක් තියෙන්නේ මට පෙනෙන විදිහට. මෙතැන ස්ක්‍රීන් ෂොට් එකක් පොස්ට් කරන්න.
```
ද + ් + ධ 	→ ද්ධ  (a dead consonant followed by a live consonant: d, dha)
ද + ් + ZWJ + ධ 	→ ද්‍ධ  (a ligated conjunct: d.dha)
ද + ZWJ + ් + ධ → ද‍්ධ  (a touching conjunct: d.dha)
```
