### ISSUE TITLE
Improve and optimize the custom compact 'Da' forms

### ISSUE THREAD

**Issue by JanakaCB** [mooniak/abhaya-libre-font#59]
The custom compact 'Da' forms comes under Stylistic Sets should be revised.

- 'දෘ' is not replaced by the subscripted glyph of the character.

- The character 'ද්‍රා' could be represented in the subscripted form to be used under Stylistic Sets, but still not available.

**Comment by pathumego** [comment]
Spotted this in මොග්ගල්ලාන පංචිකා ප්‍රදීපය - ශ්‍රී රාහුල සංඝරාජ හිමි

<img width="805" alt="Screen Shot 2021-05-30 at 5 49 00 PM" src="https://user-images.githubusercontent.com/6846609/120127063-e9d54980-c1db-11eb-82c5-f9eec0f9c185.png">
<img width="678" alt="Screen Shot 2021-05-30 at 5 48 48 PM" src="https://user-images.githubusercontent.com/6846609/120127072-ee016700-c1db-11eb-8095-5f8f71f29dfc.png">

**Comment by pathumego** [comment]
<img width="1474" alt="Screen Shot 2021-06-07 at 7 08 28 AM" src="https://user-images.githubusercontent.com/6846609/120948160-2fa38c00-c75f-11eb-90ea-c9142e6c4472.png">
