### ISSUE TITLE
Terminology 

### ISSUE THREAD

**Issue by JanakaCB** [mooniak/abhaya-libre-font#60]
For the convenience of communicating the subject matters in Sinhala, I'm going to introduce some terminology suggested by Mr. Bertram Liyanage, as shown in below image. Lets adopt this in the following discussions for the clarity and convenience.

![Terminology-01](https://user-images.githubusercontent.com/13979985/120117619-b11d7c00-c1ab-11eb-983d-8012ce203303.jpg)

**Comment by bgliyanage** [comment]
Thanks, Janaka. Here I need to add one thing. We should confine the usage of this categorization only to the technical purpose of glyph creating, for there is no practical value of this coinage of two terms in the non-technical context of language studies.

**Comment by pathumego** [comment]
I suggest these English terms to differentiate in  : Touching conjuncts = බැඳි අකුරු and ග්‍රහණාක්ෂර = fused conjuncts

**Comment by pathumego** [comment]
Hmm ’touching conjuncts’ indicates two conjuncts touching each other, what is happening here is touching two consonants. Maybe the right term is ’touching consonants’ and ’fused consonants’

**Comment by JanakaCB** [comment]
@bgliyanage agreed. 
@pathumego Lets use 'fused'. Seems it suits better than 'touching'.
