### ISSUE TITLE
Positioning Rephaya (  ර්‍ ) in between characters

### ISSUE THREAD

**Issue by JanakaCB** [mooniak/abhaya-libre-font#64]
![Screenshot 2021-06-07 122212](https://user-images.githubusercontent.com/13979985/120972303-3b0cac80-c78b-11eb-9c34-6d5dea408c1f.jpg)

![Screenshot 2021-06-07 122323](https://user-images.githubusercontent.com/13979985/120972325-4233ba80-c78b-11eb-9373-17c9d3a9c26f.jpg)

![Screenshot 2021-06-07 121837](https://user-images.githubusercontent.com/13979985/120971940-d6e9e880-c78a-11eb-80cd-30d2ea44a5f4.jpg)

Screenshots were taken from මොග්ගල්ලාන පඤ්චිකා ප්‍රදීපය - රත්මලානේ ශ්‍රීධර්මාරාම හිමි සංස්කරණය - 1896

**Comment by JanakaCB** [comment]
@bgliyanage need your clarifications for the intended instances of this positioning.

**Comment by bgliyanage** [comment]
I hereby confirm that traditionally our writing style is to write rephaya between conjunct glyphs. Here are the examples of ධර්මය, වර්ණනා, අනර්ඝ, and most importantly වීර්ය of which rephaya is not above the yamsaya but between ya and yamsaya. 
![dharma varana](https://user-images.githubusercontent.com/85128519/121033228-a1182480-c7c9-11eb-9e08-a8ea888182c2.jpeg) 
![anargha](https://user-images.githubusercontent.com/85128519/121033267-abd2b980-c7c9-11eb-8c26-c9881f3cddc8.jpeg) 
![virya](https://user-images.githubusercontent.com/85128519/121033303-b42af480-c7c9-11eb-96ab-36afe599bc92.jpeg)

**Comment by bgliyanage** [comment]
Here is another important point we must concern. When the second glyph of a conjunct has vowel markers like ispilla, then rephaya comes above the first glyph. Here are the examples of නිර්මිත and චක්‍රවති. 
![nirmita](https://user-images.githubusercontent.com/85128519/121033778-197ee580-c7ca-11eb-9c1c-bda5b9b6b3ee.jpeg) 
![varti](https://user-images.githubusercontent.com/85128519/121033830-269bd480-c7ca-11eb-9327-02526748ef7c.jpeg)

**Comment by bgliyanage** [comment]
I must mention that these photos are from the courtesy of Ven. Morawaka Dhammananda thera, who is himself a maker and scriber of ola-leaf texts.

**Comment by aluyama** [comment]
@bgliyanage සිංහල භාෂාව සම්බන්ධ ගැටලු කිහිපයක් සාකච්ඡා කිරීමට ඔබගේ වි-තැපැල් ලිපිනය ලබා ගැනීමට හැකිද? හෝ aluyama@pm.me වෙත පණිවිඩයක් එවන්න.

**Comment by pushpananda** [comment]
075 5626169
