### ISSUE TITLE
ඉස්පිල්ල සමඟ රේඵය එකවිට යෙදීම

### ISSUE THREAD

**Issue by JanakaCB** [mooniak/abhaya-libre-font#65]
![Screenshot 2021-05-31 101645](https://user-images.githubusercontent.com/13979985/120973227-490efd00-c78c-11eb-8e27-bfe4b8aa7cf4.jpg)

**Comment by JanakaCB** [comment]
සමහරවිට #64 යටතේ ඇති රේඵය අකුරු දෙකක් අතරමැදින් යෙදීම මඟින් මීට විසඳුමක් ලැබෙනු ඇත. @pathumego @bgliyanage අදහස් කියන්න.

**Comment by bgliyanage** [comment]
There is no option for this particular case of using rephaya. This is the way it has been written for a long time.

**Comment by JanakaCB** [comment]
Suggesting to add new glyphs for this combination, I upload one possible solution here to manage the space in the instances of placements of Rephya and Ispilla (and Dhirga Ispilla) one above the other. (1: Present situation  2: Suggestion)


![reph+ispilla-01](https://user-images.githubusercontent.com/13979985/121842743-90523c00-ccfe-11eb-9ebe-a4b0d154ffb8.jpg)

![reph+ispilla-02](https://user-images.githubusercontent.com/13979985/121842749-921bff80-ccfe-11eb-9a2b-08cfdc1c1468.jpg)

**Comment by pathumego** [comment]
What if we stack the Repaya on top of Ispilla and Dirga-ispilla like this?

<img width="680" alt="Screen Shot 2021-06-14 at 2 04 05 PM" src="https://user-images.githubusercontent.com/6846609/121863391-6f4b1480-cd19-11eb-8326-271dc80b2b1e.png">

**Comment by pathumego** [comment]
Implemented solution was the following;
<img width="625" alt="Screenshot 2024-02-18 at 20 38 26" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/8a29ee72-c70f-49c6-98cd-263c539b9845">

String to test
`ප්‍රියදර්‍ශිමහර්‍යි`
