### ISSUE TITLE
Windows මෙහෙයුම් පද්ධතියේ සහ MS Word වැනි යෙදවුම්ල අභය ලිබ්‍රේ රුවකුරවල ග්‍රහණක්ෂර (fused conjuncts) සහ බන්ධක්ෂර (touching conjuncts ) භාවිතයේ දෝෂය නිවැරදි කිරීම

### ISSUE THREAD

**Issue by ravincaldera** [mooniak/abhaya-libre-font#66]
OpenType සිංහල සම්මතය ග්‍රහණක්ෂර (fused conjuncts) සහ බන්ධක්ෂර (touching conjuncts ) කේතනය කරන්නේ දෙවිදිහක බව දක්වා තිබිණි. ඒ අනුව පහත ආකාරයෙන් ග්‍රහණක්ෂර හා බන්ධක්ෂර යෙදේ:
<img width="1417" alt="121630691-43baf680-ca9b-11eb-8223-c3b511e2b880" src="https://user-images.githubusercontent.com/58606701/121646313-d0bd7a00-cab2-11eb-9a39-83c86a05545a.png">
එහෙත් උක්ත දැක්වූ ආකාරකයට Windows සහ MS Wordවල අභය ලිබ්‍රේ රුවකුර ක්‍රියාත්මක වන්නේ නැත. එය මා භාවිත කරන Sinhala–Wij 9 Keyboard නිසා වන්නේ දැයි නොදනිමි. එහි ක්‍රියාත්මක වන්නේ පහත අකාරයට ය:
![Akuru](https://user-images.githubusercontent.com/58606701/121646370-dfa42c80-cab2-11eb-8e45-9c00298f310e.png)

මෙය නිවැරදි කරන ආකාරයක් පිළිබඳ දක්වන්නේ නම් මම කෘතඥ වෙමි෴

**Comment by pathumego** [comment]
@ravincaldera පහත text එක copy කරගෙන උත්සහ කරන්න. ඔබ ටයිප් කරන විදිහේ අවුලක් තියෙන්නේ මට පෙනෙන විදිහට. මෙතැන ස්ක්‍රීන් ෂොට් එකක් පොස්ට් කරන්න.
```
ද + ් + ධ 	→ ද්ධ  (a dead consonant followed by a live consonant: d, dha)
ද + ් + ZWJ + ධ 	→ ද්‍ධ  (a ligated conjunct: d.dha)
ද + ZWJ + ් + ධ → ද‍්ධ  (a touching conjunct: d.dha)
```

**Comment by ravincaldera** [comment]
ඔබ නිවැරදියි. රුවකුරෙහි ප්‍රශ්නයක් නැත. එහෙත් ටයිප් කරන විට Sinhala–Wij 9 Keyboad එක සපොට් කරන්නේ නැහැ. එබැවින් මෙම අකුරු ටයිප් කරන්න බැහැ. Microsoft මෙහෙයුම්න පද්ධතිය සඳහා වෙනත් Sinhala Keyboard එකක් තියෙනවා ද උක්ත ක්‍රමයට සපොට් කරන? 

![No_Support](https://user-images.githubusercontent.com/58606701/121663716-54cc2d80-cac4-11eb-86e2-033b2c334c19.png)

**Comment by pathumego** [comment]
@JanakaCB මේ ගැන පොඩ්ඩක් ලියන්න පුළුවන් ද? Windows වල Akuru  keyboard එක යවමු.

**Comment by ravincaldera** [comment]
දින කිහිපයක් දෙන්න. මා මෙ ගැන ලියන්නම්.

**Comment by JanakaCB** [comment]
@ravincaldera පැතුම් විසින් එවන ලද text එක ඔබගේ පරිගණක තිරයේ නිවැරදිව දිස්වන නිසා රුවකුරේ දෝෂයක් නැති බව පෙනේ. එහෙත් ඔබට එම අකුරු ටයිප් කරන්නට නොහැකි බවද කියා තිබෙන හෙයින් ගැටළුව විසඳාගැනීම සඳහා මීළඟට විමසිය යුත්තේ ඊට හේතුව; 

- Sinhala–Wij 9 Keyboard එකේ සිදුව ඇති දෝෂයක්ද? නැතහොත් 
- ඔබ විසින් input එක ලබාදීමේදී සිදුවුණු ‌දෝෂයක්ද? යන්නයි. 

ඒ බව පැහැදිලි කරගැනීමට කරුණාකර ඉහත පින්තූරයේ ඇති අකුරු පරිගණක තිරය මතට ලබාගැනීම සඳහා ඔබ විසින් ඔබගේ ඉංග්‍රීසි මාධ්‍ය යතුරු පුවරුවේ (ඔබ භාවිතා කර ඇත්තේ US Keyboard layout එක යැයි සිතමි.) යතුරු භාවිතා කරන අනුපිළිවෙල (shift යෙදීම ආදියද සහිතව) මෙහි සටහන් කරන්න.

**Comment by ravincaldera** [comment]
ස්තූතියි ඔබේ පිළිතුරට! මට හිතෙන්නේ දෝෂය ඇත්තේ Sinhala–Wij 9 Keyboard එකෙහි ය. රුවකුරෙහි දෝෂයක් නැති බව යි මගේ හැඟිම යි. එහෙත් ඔබගේ ඉල්ලීම පරිදි US Keyboard layout එකෙන් ඉහත අකුරු ටයිප් කර ඇත:

1. oaO 
2. oa\O
3. o\aO

 Sinhala–Wij 9 Keyboard එකෙහි ඇති දෝෂය මගහරවා ගැනීමට හැකි නම් මා බොහෝ ස්තුති වන්ත වෙමි.

**Comment by JanakaCB** [comment]
@ravincaldera ඔබ විසින් \ යොදා ඇති තැන් දෙකේම එය යොදා ඇත්තේ shift රහිතවද..? 

මා නම් යොදන්නේ මෙහෙමයි:

1. ද්ධ = oaO
2. ද‍්ධ (touching) = o|O
3. ද්‍ධ (fused) = o\O

කරුණාකර අභය ලිබ්‌රේ ‌රුවකුර සඳහා ඉහත අයුරින් යොදා ප්‍රතිඵල කියන්න. මෙම inputs සඳහා යතුරු භාවිතා කරන නිවැරදි අනුපිළිවෙල එයයි.

**Comment by ravincaldera** [comment]
> @ravincaldera ඔබ විසින් \ යොදා ඇති තැන් දෙකේම එය යොදා ඇත්තේ shift රහිතවද..?
> 
> මා නම් යොදන්නේ මෙහෙමයි:
> 
> 1. ද්ධ = oaO
> 2. ද‍්ධ (touching) = o|O
> 3. ද්‍ධ (fused) = o\O
> 
> කරුණාකර අභය ලිබ්‌රේ ‌රුවකුර සඳහා ඉහත අයුරින් යොදා ප්‍රතිඵල කියන්න. මෙම inputs සඳහා යතුරු භාවිතා කරන නිවැරදි අනුපිළිවෙල එයයි.

![123456](https://user-images.githubusercontent.com/58606701/121774951-68e65c80-cba2-11eb-8b1f-a3fb3f70197a.png)

මෙයින් පෙනෙන්නේ බැඳි අකුරු යතුරු ලියනය කිරීමට Sinhala–Wij 9 Keyboard එකෙක් නුපුළුවන් බවයි.

**Comment by ravincaldera** [comment]
Sinhala–Wij 9 Keyboard does not support the following construction in the [Standard for OpenType ]
(https://docs.microsoft.com/en-us/typography/script-development/sinhala#feature-examples)Fonts:

![U+0D9A U+200D U+0DCA U+0D9A](https://user-images.githubusercontent.com/58606701/121775366-c24f8b00-cba4-11eb-98d1-e9736eb50bae.png)  
U+0D9A U+200D U+0DCA U+0D9A

**Comment by JanakaCB** [comment]
@ravincaldera ඔබට ඇති ගැටළුව මුළුමනින්ම විජේසේකර යතුරු පුවරුවේ ගැටළුවක් යැයි කියනවාට වඩා නිවැරදි වන්නේ වින්ඩෝස් මෙහෙයුම් පද්ධතියේ (සමහර version වල පමණක් ඇති බවට හඳුනාගෙන තිබෙන) විජේසේකර යතුරු පුවරුවට සම්බන්ධ bug එකකින් සිදුවන්නක් බවයි.

පහත සබැඳියෙන් එවන අකුරු එකතුව විසින් සකස්කළ එම වරද නිවැරදි කරන ලද යතුරු පුවරුව පරිගණකයට ඇතුලත් කරගන්න. ගැටළුව විසඳේවි.

ද‍්ධ (touching) = o|O ආදී ලෙසින් touching සඳහා සෑමවිටම මා අංක 2 යටතේ පෙන්වා ඇති ආකාරය හෙවත් | ලකුණ යොදාගැනීම (හෙවත් Shift+\) ආකාරය භාවිත කරන්න. අනෙකුත් සෑම touching අකුරු ආකාරයක්මත් ඒ ක්‍රමයෙන් නිවැරදිව ක්‍රියාත්මක වනු ඇති. 

https://drive.google.com/drive/folders/1oiJgRpxcveP1CiXcWAfxQtDHKI65yKzQ?usp=sharing

**Comment by ravincaldera** [comment]
බොහොම ස්තූතියි!

**Comment by JanakaCB** [comment]
ඔබට උදව් කරන්නට ලැබීම අපට සතුටක් ෴෴෴
