### ISSUE TITLE
custom compact " ද්‍යා් " glyph is not working

### ISSUE THREAD

**Issue by JanakaCB** [mooniak/abhaya-libre-font#73]
This glyph does not invokes under the relevant stylistic set setting.

**Comment by pathumego** [comment]
@JanakaCB Can you please test with this latest font build and post an update? 
https://github.com/mooniak/abhaya-libre-font/blob/main/fonts/variable/AbhayaLibre%5Bwght%5D.ttf

**Comment by JanakaCB** [comment]
When checked with the version mentioned above, it works perfectly. Moreover, it needs a following character (a letter or a space, NOT the Return/Enter command) to invoke the combination correctly. Please take a look at the image below. 

<img width="312" alt="Screenshot 2023-10-17 at 23 24 03" src="https://github.com/mooniak/abhaya-libre-font/assets/13979985/1e4bdd6d-6f8e-41df-b911-6599bb3e70f9">

Why does it want this following character to invoke the correct combination? (Anyhow, there are about zero instances when it will be used without a following letter or space. So, it could have remained as it is without any tweak until someone reports there is a use case. 


**
For someone interested to know what this issue is all about, I am adding some context below:

The glyph mentioned above - ද්‍යා් - should not invoke the stylistic set, but  ද්‍යෝ  should. Think of it like this:

Can you type any of these - යා් මා් පා් - in Unicode? No. Because there is no use of that combination without the Kombuwa - ෙ - in front of them. Suppose you place a Kombuwa in front, and then they become valid combinations such as  යෝ මෝ පෝ, and likewise if you put a Kombuwa in front of  ද්‍යා් , it will invoke the custom compact glyph  ද්‍යෝ  without any issue.
