### ISSUE TITLE
ඉස්පිලි ආදිය නිවැරදිව ටයිප් කිරීම

### ISSUE THREAD

**Issue by RushKodi** [mooniak/abhaya-libre-font#76]
මා වින්ඩෝස් 10 මෙහෙයුම් පද්ධතිය තුළ විජේසේකර යතුරු පුවරුව භාවිතා කරමි. ඇඩෝබේ ඉන්ඩිසයින් මෘදුකාංගය තුළ අභය ලිබ්රේ රුවකුර භාවිතා කිරීමේදී ඉස්පිලි, පාපිලි ආදිය නිවැරදිව ටයිප් නොවේ. එෆ්.එම්. රුවකුරු භාවිතයේදී ඉස්පිලි ආදිය සකසා ගැනීමට කීහෙල්ප් මෘදුකාංගය භාවිත කළද, එය අභය ලිබ්රේ රුවකුර සදහා සහාය නොවේ. 

මේ ගැටළුව සදහා සහාය පතමි. ස්තුතියි

![image](https://user-images.githubusercontent.com/112111726/186726294-7395586b-c484-4d45-b4dd-0d1dee9045ea.png)

**Comment by JanakaCB** [comment]
අභය ලිබ්රේ රුවකුර යුනිකෝඩ් සම්මතය යටතේ නිපදවා ඇති රුවකුරකි. එය පරිගණකයක භාවිතා කිරීම සඳහා කිසිඳු අමතර මෘදුකාංගයක් අවශ්‍ය නැත. එහෙත් ඒ සඳහා ඔබේ පරිගණකයේ සිංහල පහසුකම ස්ථාපනය කරගෙන තිබිය යුතුය. ඔබගේ මෙහෙයුම් පද්ධතිය, ඇඩෝබේ ඉන්ඩිසයින් මෘදුකාංගය වැනි අදාල මෘදුකාංග සියල්ල යාවත්කාලීන කර තිබිය යුතුය. එසේ යාවත්කාලීන කර ඇත්නම්:

ඇඩෝබේ ඉන්ඩිසයින් හි Preferences  Advanced Type Default Composer යටතේ ඇති Adobe World-Ready Paragraph Composer තෝරන්න. තෝරාගැනීම Save කර ඉන්ඩිසයින් close කර නැවත open කරන්න. 

<img width="419" alt="Screenshot 2022-08-26 at 10 38 27" src="https://user-images.githubusercontent.com/13979985/186826802-1d227547-61c0-4b87-bd24-073f90093187.png">

ඉන්පසු ඔබේ පරිගණකයේ input method එක ලෙස සිංහල යතුරුපුවරුව තෝරා සාමාන්‍ය පරිදි විජේසේකර යතුරු පුවරුවෙන් ටයිප් කරන්න. 

<img width="960" alt="Screenshot 2022-08-26 at 10 37 52" src="https://user-images.githubusercontent.com/13979985/186826815-92c018d7-e6d3-46ad-ad9c-27dfbff5fbf3.png">
