### ISSUE TITLE
Sinhala Archaic Numerals should be added

### ISSUE THREAD

**Issue by JanakaCB** [mooniak/abhaya-libre-font#77]
Thanks to the team, the Sinhala Lith Digits are there now. But Sinhala Archaic Numerals should be added. 

Issue #13 brings this up, but it seems it was closed after adding the Lith Digit set. So, we still have to complete the task.

Thank you.

Reference: http://unicode.org/charts/PDF/U111E0.pdf

**Comment by pathumego** [comment]
@JanakaCB Already added in the Dev versions of the font. Will email you to test.

<img width="569" alt="Screenshot 2023-10-13 at 13 02 10" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/bd6a1a33-2b3b-4d6b-bfff-0e8bf1857deb">
[AbhayaLibre_archiac-numerals-test.pdf](https://github.com/mooniak/abhaya-libre-font/files/12890732/AbhayaLibre_archiac-numerals-test.pdf)
