### ISSUE TITLE
Lith digit Zero - Above Baseline Position ?

### ISSUE THREAD

**Issue by JanakaCB** [mooniak/abhaya-libre-font#85]
The Abhaya Libre Lith Digit Zero is placed above the baseline. But if we cross reference against Noto Sans Sinhala, Nirmala UI, and Galle Alpha, all seem to choose to place the Zero exactly on the baseline. Is there a specific reason to put the Zero above the baseline against all the other three mentioned fonts? Image attached. 

![AL issues](https://github.com/mooniak/abhaya-libre-font/assets/13979985/343a8c5a-64c5-4170-beab-dcacda0f799b)

**Comment by kosalaya** [comment]
//The Abhaya Libre Lith Digit Zero is placed above the baseline. But if we cross reference against Noto Sans Sinhala, Nirmala UI, and Galle Alpha, all seem to choose to place the Zero exactly on the baseline.// 

No specific reason for this, now rectified. How come the five glyphs in the middle are missing?

**Comment by pathumego** [comment]
> How come the five glyphs in the middle are missing?

@JanakaCB ?

**Comment by JanakaCB** [comment]
I checked once again. It is due to a bug in the previous dev version, named the 'Abhaya Libre DEV.' After uninstalling it, there is no issue.
