### ISSUE TITLE
Increase blob weight

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#88]
<img width="524" alt="Screenshot 2024-01-02 at 11 23 18" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/0e724bdf-849a-413c-8cc0-bd3a50ffaf33">

**Comment by kosalaya** [comment]
<img width="952" alt="Screenshot 2024-02-16 at 09 43 14" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/98e67dfc-684d-4ca1-88cd-4e89aca5d975">
