### ISSUE TITLE
ன is leaning left

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#90]
<img width="287" alt="Screenshot 2024-01-02 at 11 26 52" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/252c96a3-a17c-4020-99a2-ea0ff6c20a4d">

**Comment by kosalaya** [comment]
<img width="1135" alt="Screenshot 2024-02-16 at 10 25 59" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/85e6fe0d-6837-4b4a-b89f-191eb972a5e3">
