### ISSUE TITLE
கு, ரு fix the curve

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#91]
<img width="503" alt="Screenshot 2024-01-02 at 11 28 54" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/9a7a3084-152a-410e-87a6-9865fd77d793">

**Comment by pathumego** [comment]
<img width="378" alt="Screenshot 2024-01-02 at 11 31 17" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/697b0684-34c6-4ed4-8145-ed88abb1dd35">

**Comment by kosalaya** [comment]
<img width="1359" alt="Screenshot 2024-02-16 at 10 23 29" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/d7f67999-3637-4cde-ba9f-dcfeaa157a5e">
