### ISSUE TITLE
ய redistribute space

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#92]
<img width="503" alt="Screenshot 2024-01-02 at 11 28 54" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/8c56a978-3957-421e-9dca-ec04b8931556">

**Comment by kosalaya** [comment]
<img width="1277" alt="Screenshot 2024-02-16 at 10 21 46" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/4c98f1de-d8f9-4074-ad6b-ad95636d05c4">
