### ISSUE TITLE
ல lighter upstroke

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#93]
<img width="426" alt="Screenshot 2024-01-02 at 11 32 10" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/9da89f45-e069-45ba-8410-12fd1d959fe1">

**Comment by kosalaya** [comment]
<img width="939" alt="Screenshot 2024-02-16 at 10 16 47" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/f7e14f91-a42f-458b-8d82-2a829a9c6ede">
