### ISSUE TITLE
டி make the loop a bit wider

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#94]
<img width="426" alt="Screenshot 2024-01-02 at 11 32 56" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/65f38788-d700-4e38-a66c-548802a267ea">

**Comment by kosalaya** [comment]
<img width="1150" alt="Screenshot 2024-02-16 at 10 18 36" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/7fe0173d-2739-4cef-bbaf-49d2c71dce66">
