### ISSUE TITLE
Make e Matra loop bigger 

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#95]
<img width="452" alt="Screenshot 2024-01-02 at 11 34 07" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/0787c26e-a5f2-4797-85af-709630393f07">

**Comment by kosalaya** [comment]
<img width="1115" alt="Screenshot 2024-02-16 at 10 09 55" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/e287b832-66c2-4b1b-8139-fa9133e214bb">
