### ISSUE TITLE
ஓ move a bit lower

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#96]
<img width="616" alt="Screenshot 2024-01-02 at 11 37 31" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/660a4cb8-d758-433a-bb62-20c981cc1fbf">

**Comment by kosalaya** [comment]
<img width="1013" alt="Screenshot 2024-02-16 at 10 06 45" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/25ad7285-b4f8-4637-a0fb-a6ab4cea457a">
