### ISSUE TITLE
Recheck pulli placements across masters

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#97]
<img width="447" alt="Screenshot 2024-01-02 at 11 38 40" src="https://github.com/mooniak/abhaya-libre-font/assets/6846609/47bb069b-139e-4e95-b243-c8d338015f8a">

**Comment by kosalaya** [comment]
![Uploading Screenshot 2024-02-16 at 10.00.42.png…]()

**Comment by kosalaya** [comment]
<img width="1280" alt="Screenshot 2024-02-16 at 10 00 42" src="https://github.com/mooniak/abhaya-libre-font/assets/8073976/574e171e-2498-4766-8ede-ef3c5b3eabe9">
